# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'SaltLakeChristianChurch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SaltLakeChristianChurch

#Firebase
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'Firebase/Core'

#Keyboard Manager
pod 'IQKeyboardManager'

#Phonenumber Manager
source 'https://github.com/CocoaPods/Specs.git'
pod 'PhoneNumberKit', '~> 2.1'

#Ambience
pod 'Ambience'

target 'SaltLakeChristianChurchTests' do
    inherit! :search_paths
    pod 'Firebase'
end
end
